# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- vegeta-ns-1.yaml
- vegeta-ns-2.yaml
- vegeta-ns-3.yaml
- vegeta-ns-4.yaml
- vegeta-ns-5.yaml
- vegeta-ns-6.yaml
- vegeta-ns-7.yaml
- vegeta-ns-8.yaml
- vegeta-ns-9.yaml
- vegeta-ns-10.yaml
- vegeta-ns-11.yaml
- vegeta-ns-12.yaml
- vegeta-ns-13.yaml
- vegeta-ns-14.yaml
- vegeta-ns-15.yaml
- vegeta-ns-16.yaml
- vegeta-ns-17.yaml
- vegeta-ns-18.yaml
- vegeta-ns-19.yaml
- vegeta-ns-20.yaml
- vegeta-ns-21.yaml
- vegeta-ns-22.yaml
- vegeta-ns-23.yaml
- vegeta-ns-24.yaml
- vegeta-ns-25.yaml

# patch nodeSelector and tolerations on all Deployments
patches:
- patch: |-
    kind: not-important
    metadata:
      name: not-important
    spec:
      template:
        spec:
          tolerations:
          - key: "loadgen"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
  target:
    kind: Deployment
