
apiVersion: v1
kind: Namespace
metadata:
  name: ns-7
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tier-1-app-a
  namespace: ns-7
  labels:
    app: tier-1-app-a
    tier: "1" 
---
apiVersion: v1
kind: Service
metadata:
  name: tier-1-app-a
  namespace: ns-7
  labels:
    app: tier-1-app-a
    tier: "1"
spec:
  selector:
    app: tier-1-app-a
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tier-1-app-a
  namespace: ns-7
  labels:
    app: tier-1-app-a
    tier: "1"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app: tier-1-app-a
  template:
    metadata:
      labels:
        app: tier-1-app-a
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tier-1-app-a
              namespaceSelector: {}
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: tier-1-app-a
      containers:
      - name: tier-1-app-a
        image: nicholasjackson/fake-service:v0.26.2
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1001
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "NAME"
          value: "tier-1-app-a"
        - name: "SERVER_TYPE"
          value: "http"
        - name: "MESSAGE"
          value: "Hello From tier-1-app-a!"
        - name: "UPSTREAM_URIS"
          value: "http://tier-2-app-a.ns-7:8080,http://tier-2-app-b.ns-7:8080"
        - name: "UPSTREAM_WORKERS"
          value: "1"
        - name: "TIMING_50_PERCENTILE"
          value: "0ms"
        - name: "TIMING_90_PERCENTILE"
          value: "0ms"
        - name: "TIMING_99_PERCENTILE"
          value: "0ms"
        - name: "HTTP_CLIENT_REQUEST_TIMEOUT"
          value: "30s"
        - name: "HTTP_SERVER_KEEP_ALIVES"
          value: "true"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "true"
        # guaranteed qos  
        resources:
          requests:
            cpu: "700m"
            memory: "500Mi"
          limits:
            cpu: "700m"
            memory: "500Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tier-1-app-b
  namespace: ns-7
  labels:
    app: tier-1-app-b
    tier: "1" 
---
apiVersion: v1
kind: Service
metadata:
  name: tier-1-app-b
  namespace: ns-7
  labels:
    app: tier-1-app-b
    tier: "1"
spec:
  selector:
    app: tier-1-app-b
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tier-1-app-b
  namespace: ns-7
  labels:
    app: tier-1-app-b
    tier: "1"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app: tier-1-app-b
  template:
    metadata:
      labels:
        app: tier-1-app-b
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tier-1-app-b
              namespaceSelector: {}
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: tier-1-app-b
      containers:
      - name: tier-1-app-b
        image: nicholasjackson/fake-service:v0.26.2
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1001
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "NAME"
          value: "tier-1-app-b"
        - name: "SERVER_TYPE"
          value: "http"
        - name: "MESSAGE"
          value: "Hello From tier-1-app-b!"
        - name: "UPSTREAM_URIS"
          value: "http://tier-2-app-c.ns-7:8080,http://tier-2-app-d.ns-7:8080"
        - name: "UPSTREAM_WORKERS"
          value: "1"
        - name: "TIMING_50_PERCENTILE"
          value: "0ms"
        - name: "TIMING_90_PERCENTILE"
          value: "0ms"
        - name: "TIMING_99_PERCENTILE"
          value: "0ms"
        - name: "HTTP_CLIENT_REQUEST_TIMEOUT"
          value: "1s"
        - name: "HTTP_SERVER_KEEP_ALIVES"
          value: "true"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "true"
        # guaranteed qos  
        resources:
          requests:
            cpu: "700m"
            memory: "500Mi"
          limits:
            cpu: "700m"
            memory: "500Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tier-2-app-a
  namespace: ns-7
  labels:
    app: tier-2-app-a
    tier: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: tier-2-app-a
  namespace: ns-7
  labels:
    app: tier-2-app-a
    tier: "2"
spec:
  selector:
    app: tier-2-app-a
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tier-2-app-a
  namespace: ns-7
  labels:
    app: tier-2-app-a
    tier: "2"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app: tier-2-app-a
  template:
    metadata:
      labels:
        app: tier-2-app-a
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tier-2-app-a
              namespaceSelector: {}
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: tier-2-app-a
      containers:
      - name: tier-2-app-a
        image: nicholasjackson/fake-service:v0.26.2
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1001
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "NAME"
          value: "tier-2-app-a"
        - name: "SERVER_TYPE"
          value: "http"
        - name: "MESSAGE"
          value: "Hello From tier-2-app-a!"
        - name: "UPSTREAM_URIS"
          value: "http://tier-3-app-a.ns-7:8080"
        - name: "UPSTREAM_WORKERS"
          value: "1"
        - name: "TIMING_50_PERCENTILE"
          value: "0ms"
        - name: "TIMING_90_PERCENTILE"
          value: "0ms"
        - name: "TIMING_99_PERCENTILE"
          value: "0ms"
        - name: "HTTP_CLIENT_REQUEST_TIMEOUT"
          value: "30s"
        - name: "HTTP_SERVER_KEEP_ALIVES"
          value: "true"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "true"
        # guaranteed qos  
        resources:
          requests:
            cpu: "700m"
            memory: "500Mi"
          limits:
            cpu: "700m"
            memory: "500Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tier-2-app-b
  namespace: ns-7
  labels:
    app: tier-2-app-b
    tier: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: tier-2-app-b
  namespace: ns-7
  labels:
    app: tier-2-app-b
    tier: "2"
spec:
  selector:
    app: tier-2-app-b
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tier-2-app-b
  namespace: ns-7
  labels:
    app: tier-2-app-b
    tier: "2"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app: tier-2-app-b
  template:
    metadata:
      labels:
        app: tier-2-app-b
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tier-2-app-b
              namespaceSelector: {}
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: tier-2-app-b
      containers:
      - name: tier-2-app-b
        image: nicholasjackson/fake-service:v0.26.2
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1001
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "NAME"
          value: "tier-2-app-b"
        - name: "SERVER_TYPE"
          value: "http"
        - name: "MESSAGE"
          value: "Hello From tier-2-app-b!"
        - name: "UPSTREAM_URIS"
          value: "http://tier-3-app-a.ns-7:8080"
        - name: "UPSTREAM_WORKERS"
          value: "1"
        - name: "TIMING_50_PERCENTILE"
          value: "0ms"
        - name: "TIMING_90_PERCENTILE"
          value: "0ms"
        - name: "TIMING_99_PERCENTILE"
          value: "0ms"
        - name: "HTTP_CLIENT_REQUEST_TIMEOUT"
          value: "30s"
        - name: "HTTP_SERVER_KEEP_ALIVES"
          value: "true"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "true"
        # guaranteed qos  
        resources:
          requests:
            cpu: "700m"
            memory: "500Mi"
          limits:
            cpu: "700m"
            memory: "500Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tier-2-app-c
  namespace: ns-7
  labels:
    app: tier-2-app-c
    tier: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: tier-2-app-c
  namespace: ns-7
  labels:
    app: tier-2-app-c
    tier: "2"
spec:
  selector:
    app: tier-2-app-c
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tier-2-app-c
  namespace: ns-7
  labels:
    app: tier-2-app-c
    tier: "2"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app: tier-2-app-c
  template:
    metadata:
      labels:
        app: tier-2-app-c
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tier-2-app-c
              namespaceSelector: {}
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: tier-2-app-c
      containers:
      - name: tier-2-app-c
        image: nicholasjackson/fake-service:v0.26.2
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1001
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "NAME"
          value: "tier-2-app-c"
        - name: "SERVER_TYPE"
          value: "http"
        - name: "MESSAGE"
          value: "Hello From tier-2-app-c!"
        - name: "UPSTREAM_URIS"
          value: "http://tier-3-app-b.ns-7:8080"
        - name: "UPSTREAM_WORKERS"
          value: "1"
        - name: "TIMING_50_PERCENTILE"
          value: "0ms"
        - name: "TIMING_90_PERCENTILE"
          value: "0ms"
        - name: "TIMING_99_PERCENTILE"
          value: "0ms"
        - name: "HTTP_CLIENT_REQUEST_TIMEOUT"
          value: "30s"
        - name: "HTTP_SERVER_KEEP_ALIVES"
          value: "true"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "true"
        # guaranteed qos  
        resources:
          requests:
            cpu: "700m"
            memory: "500Mi"
          limits:
            cpu: "700m"
            memory: "500Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tier-2-app-d
  namespace: ns-7
  labels:
    app: tier-2-app-d
    tier: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: tier-2-app-d
  namespace: ns-7
  labels:
    app: tier-2-app-d
    tier: "2"
spec:
  selector:
    app: tier-2-app-d
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tier-2-app-d
  namespace: ns-7
  labels:
    app: tier-2-app-d
    tier: "2"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app: tier-2-app-d
  template:
    metadata:
      labels:
        app: tier-2-app-d
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tier-2-app-d
              namespaceSelector: {}
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: tier-2-app-d
      containers:
      - name: tier-2-app-d
        image: nicholasjackson/fake-service:v0.26.2
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1001
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "NAME"
          value: "tier-2-app-d"
        - name: "SERVER_TYPE"
          value: "http"
        - name: "MESSAGE"
          value: "Hello From tier-2-app-d!"
        - name: "UPSTREAM_URIS"
          value: "http://tier-3-app-b.ns-7:8080"
        - name: "UPSTREAM_WORKERS"
          value: "1"
        - name: "TIMING_50_PERCENTILE"
          value: "0ms"
        - name: "TIMING_90_PERCENTILE"
          value: "0ms"
        - name: "TIMING_99_PERCENTILE"
          value: "0ms"
        - name: "HTTP_CLIENT_REQUEST_TIMEOUT"
          value: "30s"
        - name: "HTTP_SERVER_KEEP_ALIVES"
          value: "true"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "true"
        # guaranteed qos  
        resources:
          requests:
            cpu: "700m"
            memory: "500Mi"
          limits:
            cpu: "700m"
            memory: "500Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tier-3-app-a
  namespace: ns-7
  labels:
    app: tier-3-app-a
    tier: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: tier-3-app-a
  namespace: ns-7
  labels:
    app: tier-3-app-a
    tier: "2"
spec:
  selector:
    app: tier-3-app-a
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tier-3-app-a
  namespace: ns-7
  labels:
    app: tier-3-app-a
    tier: "2"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app: tier-3-app-a
  template:
    metadata:
      labels:
        app: tier-3-app-a
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tier-3-app-a
              namespaceSelector: {}
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: tier-3-app-a
      containers:
      - name: tier-3-app-a
        image: nicholasjackson/fake-service:v0.26.2
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1001
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "NAME"
          value: "tier-3-app-a"
        - name: "SERVER_TYPE"
          value: "http"
        - name: "MESSAGE"
          value: "Hello From tier-3-app-a!"
        - name: "UPSTREAM_URIS"
          value: ""
        - name: "UPSTREAM_WORKERS"
          value: "1"
        - name: "TIMING_50_PERCENTILE"
          value: "0ms"
        - name: "TIMING_90_PERCENTILE"
          value: "0ms"
        - name: "TIMING_99_PERCENTILE"
          value: "0ms"
        - name: "HTTP_CLIENT_REQUEST_TIMEOUT"
          value: "30s"
        - name: "HTTP_SERVER_KEEP_ALIVES"
          value: "true"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "true"
        # guaranteed qos  
        resources:
          requests:
            cpu: "700m"
            memory: "500Mi"
          limits:
            cpu: "700m"
            memory: "500Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tier-3-app-b
  namespace: ns-7
  labels:
    app: tier-3-app-b
    tier: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: tier-3-app-b
  namespace: ns-7
  labels:
    app: tier-3-app-b
    tier: "2"
spec:
  selector:
    app: tier-3-app-b
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tier-3-app-b
  namespace: ns-7
  labels:
    app: tier-3-app-b
    tier: "2"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app: tier-3-app-b
  template:
    metadata:
      labels:
        app: tier-3-app-b
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tier-3-app-b
              namespaceSelector: {}
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: tier-3-app-b
      containers:
      - name: tier-3-app-b
        image: nicholasjackson/fake-service:v0.26.2
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1001
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "NAME"
          value: "tier-3-app-b"
        - name: "SERVER_TYPE"
          value: "http"
        - name: "MESSAGE"
          value: "Hello From tier-3-app-b!"
        - name: "UPSTREAM_URIS"
          value: ""
        - name: "UPSTREAM_WORKERS"
          value: "1"
        - name: "TIMING_50_PERCENTILE"
          value: "0ms"
        - name: "TIMING_90_PERCENTILE"
          value: "0ms"
        - name: "TIMING_99_PERCENTILE"
          value: "0ms"
        - name: "HTTP_CLIENT_REQUEST_TIMEOUT"
          value: "30s"
        - name: "HTTP_SERVER_KEEP_ALIVES"
          value: "true"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "true"
        # guaranteed qos  
        resources:
          requests:
            cpu: "700m"
            memory: "500Mi"
          limits:
            cpu: "700m"
            memory: "500Mi"
