apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: tier-1-app-a-viewer
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: tier-1-app-a
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istio-ingressgateway
        - cluster.local/ns/client/sa/sleep
        - cluster.local/ns/ns-1/sa/vegeta1
        - cluster.local/ns/ns-2/sa/vegeta1
        - cluster.local/ns/ns-3/sa/vegeta1
        - cluster.local/ns/ns-4/sa/vegeta1
        - cluster.local/ns/ns-5/sa/vegeta1
        - cluster.local/ns/ns-6/sa/vegeta1
        - cluster.local/ns/ns-7/sa/vegeta1
        - cluster.local/ns/ns-8/sa/vegeta1
        - cluster.local/ns/ns-9/sa/vegeta1
        - cluster.local/ns/ns-10/sa/vegeta1
        - cluster.local/ns/ns-11/sa/vegeta1
        - cluster.local/ns/ns-12/sa/vegeta1
        - cluster.local/ns/ns-13/sa/vegeta1
        - cluster.local/ns/ns-14/sa/vegeta1
        - cluster.local/ns/ns-15/sa/vegeta1
        - cluster.local/ns/ns-16/sa/vegeta1
        - cluster.local/ns/ns-17/sa/vegeta1
        - cluster.local/ns/ns-18/sa/vegeta1
        - cluster.local/ns/ns-19/sa/vegeta1
        - cluster.local/ns/ns-20/sa/vegeta1
        - cluster.local/ns/ns-21/sa/vegeta1
        - cluster.local/ns/ns-22/sa/vegeta1
        - cluster.local/ns/ns-23/sa/vegeta1
        - cluster.local/ns/ns-24/sa/vegeta1
        - cluster.local/ns/ns-25/sa/vegeta1
        - cluster.local/ns/ns-1/sa/waypoint
        - cluster.local/ns/ns-2/sa/waypoint
        - cluster.local/ns/ns-3/sa/waypoint
        - cluster.local/ns/ns-4/sa/waypoint
        - cluster.local/ns/ns-5/sa/waypoint
        - cluster.local/ns/ns-6/sa/waypoint
        - cluster.local/ns/ns-7/sa/waypoint
        - cluster.local/ns/ns-8/sa/waypoint
        - cluster.local/ns/ns-9/sa/waypoint
        - cluster.local/ns/ns-10/sa/waypoint
        - cluster.local/ns/ns-11/sa/waypoint
        - cluster.local/ns/ns-12/sa/waypoint
        - cluster.local/ns/ns-13/sa/waypoint
        - cluster.local/ns/ns-14/sa/waypoint
        - cluster.local/ns/ns-15/sa/waypoint
        - cluster.local/ns/ns-16/sa/waypoint
        - cluster.local/ns/ns-17/sa/waypoint
        - cluster.local/ns/ns-18/sa/waypoint
        - cluster.local/ns/ns-19/sa/waypoint
        - cluster.local/ns/ns-20/sa/waypoint
        - cluster.local/ns/ns-21/sa/waypoint
        - cluster.local/ns/ns-22/sa/waypoint
        - cluster.local/ns/ns-23/sa/waypoint
        - cluster.local/ns/ns-24/sa/waypoint
        - cluster.local/ns/ns-25/sa/waypoint
