apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: tier-2-app-d-viewer
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: tier-2-app-d
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/client/sa/sleep
        - cluster.local/ns/ns-1/sa/tier-1-app-b
        - cluster.local/ns/ns-2/sa/tier-1-app-b
        - cluster.local/ns/ns-3/sa/tier-1-app-b
        - cluster.local/ns/ns-4/sa/tier-1-app-b
        - cluster.local/ns/ns-5/sa/tier-1-app-b
        - cluster.local/ns/ns-6/sa/tier-1-app-b
        - cluster.local/ns/ns-7/sa/tier-1-app-b
        - cluster.local/ns/ns-8/sa/tier-1-app-b
        - cluster.local/ns/ns-9/sa/tier-1-app-b
        - cluster.local/ns/ns-10/sa/tier-1-app-b
        - cluster.local/ns/ns-11/sa/tier-1-app-b
        - cluster.local/ns/ns-12/sa/tier-1-app-b
        - cluster.local/ns/ns-13/sa/tier-1-app-b
        - cluster.local/ns/ns-14/sa/tier-1-app-b
        - cluster.local/ns/ns-15/sa/tier-1-app-b
        - cluster.local/ns/ns-16/sa/tier-1-app-b
        - cluster.local/ns/ns-17/sa/tier-1-app-b
        - cluster.local/ns/ns-18/sa/tier-1-app-b
        - cluster.local/ns/ns-19/sa/tier-1-app-b
        - cluster.local/ns/ns-20/sa/tier-1-app-b
        - cluster.local/ns/ns-21/sa/tier-1-app-b
        - cluster.local/ns/ns-22/sa/tier-1-app-b
        - cluster.local/ns/ns-23/sa/tier-1-app-b
        - cluster.local/ns/ns-24/sa/tier-1-app-b
        - cluster.local/ns/ns-25/sa/tier-1-app-b
        - cluster.local/ns/ns-26/sa/tier-1-app-b
        - cluster.local/ns/ns-27/sa/tier-1-app-b
        - cluster.local/ns/ns-28/sa/tier-1-app-b
        - cluster.local/ns/ns-29/sa/tier-1-app-b
        - cluster.local/ns/ns-30/sa/tier-1-app-b
        - cluster.local/ns/ns-1/sa/waypoint
        - cluster.local/ns/ns-2/sa/waypoint
        - cluster.local/ns/ns-3/sa/waypoint
        - cluster.local/ns/ns-4/sa/waypoint
        - cluster.local/ns/ns-5/sa/waypoint
        - cluster.local/ns/ns-6/sa/waypoint
        - cluster.local/ns/ns-7/sa/waypoint
        - cluster.local/ns/ns-8/sa/waypoint
        - cluster.local/ns/ns-9/sa/waypoint
        - cluster.local/ns/ns-10/sa/waypoint
        - cluster.local/ns/ns-11/sa/waypoint
        - cluster.local/ns/ns-12/sa/waypoint
        - cluster.local/ns/ns-13/sa/waypoint
        - cluster.local/ns/ns-14/sa/waypoint
        - cluster.local/ns/ns-15/sa/waypoint
        - cluster.local/ns/ns-16/sa/waypoint
        - cluster.local/ns/ns-17/sa/waypoint
        - cluster.local/ns/ns-18/sa/waypoint
        - cluster.local/ns/ns-19/sa/waypoint
        - cluster.local/ns/ns-20/sa/waypoint
        - cluster.local/ns/ns-21/sa/waypoint
        - cluster.local/ns/ns-22/sa/waypoint
        - cluster.local/ns/ns-23/sa/waypoint
        - cluster.local/ns/ns-24/sa/waypoint
        - cluster.local/ns/ns-25/sa/waypoint
        - cluster.local/ns/ns-26/sa/waypoint
        - cluster.local/ns/ns-27/sa/waypoint
        - cluster.local/ns/ns-28/sa/waypoint
        - cluster.local/ns/ns-29/sa/waypoint
        - cluster.local/ns/ns-30/sa/waypoint
